services:
  tunnel:
    container_name: cloudflared-beebot
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file: 
      - stack.env
    networks:
      - default

  soundbored:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - /mnt/media/soundboard:/app/priv/static/uploads
    tmpfs:
      - /tmp/mix_pubsub:mode=0777
    user: "1000:1000"
    read_only: true
    environment:
      TMPDIR: /tmp/mix_pubsub
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      PHX_HOST: beebot.win
      SCHEME: https
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      AUTO_JOIN: ${AUTO_JOIN}
      DISCORD_REQUIRED_GUILD_ID: ${DISCORD_REQUIRED_GUILD_ID}
      DISCORD_ROLE_GUILD_ID: ${DISCORD_ROLE_GUILD_ID}
      DISCORD_UPLOAD_ROLE_IDS: ${DISCORD_UPLOAD_ROLE_IDS}
      DISCORD_PLAY_ROLE_IDS: ${DISCORD_PLAY_ROLE_IDS}
      DISCORD_SETTINGS_ADMIN_USER_ID: ${DISCORD_SETTINGS_ADMIN_USER_ID}
